---
- name: Execute show arp
  hosts: all
  connection: local                       # code is run locally
  gather_facts: no
  tasks:
    - raw: "show arp"
      register: result
    - debug: var=result.stdout_lines
