---
- hosts: all
  connection: local                       # code is run locally
  gather_facts: no                        # don't gather facts

  vars:
    result_dir: ./roles/compliance/files
    root_dir: ./

  tasks:
  - name: Generate a log file
    shell:
      cmd: "pwd"
