---
- hosts: all
  gather_facts: no
  vars:
    version: 15.4

  tasks:
  - name: Read in parse_genie role
    include_role:
      name: clay584.parse_genie

  - name: Get Data From Device
    ios_command:
      commands: show arp
    register: arp_output

  - name: Print Structured Data
    debug:
      msg: "{{ arp_output['stdout'][0] | parse_genie(command='show arp', os='ios') }}"
    delegate_to: localhost