---
- hosts: r2
  gather_facts: false
  connection: local

  tasks:
   - name: run show version and check to see if output contains IOS
     ios_command:
      commands: show version
      wait_for: result[0] contains IOS

   - name: Configure ACL on Cisco Switch
     ios_config:
       authorize: yes
       lines:
         - access-list 99 permit 172.16.1.100

   - name: Verify ACL is present
     ios_command:
       commands:
         - sh access-l
       waitfor:
         - result[0] contains 'permit 172.16.1.100'

   - name: run multiple commands and evaluate the output
     ios_command:
       commands:
         - show version
         - show interfaces
       wait_for:
         - result[0] contains IOS
         - result[1] contains Loopback0

   - name: SAVE CONFIG
     ios_command:
       commands:
         - write memory
