---
### Variables declaration ###
- hosts: ios
  vars:
    commands:
      - "show ip ospf {{ process.id }}"
      - "show ip ospf {{ process.id }} neighbor"
      - "show ip ospf {{ process.id }} database database-summary"
      - "show ip ospf {{ process.id }} traffic"
      #- "show ip ospf {{ process.id }} fast-reroute"
      #- "show bfd neighbor client ospf"
      - "show ip ospf {{ process.id }} interface"  # not parsed
      - "show ip ospf {{ process.id }} database"  # not parsed
      - "show version"  # not parsed
    process:
      id: 1
      has_ispf: true
      has_bfd: true
      has_ttlsec: true
      ref_bw: 1000
      max_lsa5: 5000
      hosts: all
      gather_facts: no

### Playbook tasks ###

  name: "BLOCK >> Get data, log, and parse from device"
  tasks:
    - name: "IOS >> Collect OSPF PID {{ process.id }} info from routers"
      ios_command:
        commands: "{{ commands }}"
      register: CLI_OUTPUT

    - name: "DEBUG >> Write CLI  output (stdout) to console"
      debug:
        #var: CLI_OUTPUT
        msg: "{{ CLI_OUTPUT.stdout_lines | to_nice_json }}"
        #verbosity: 1

    - name: "LOG >> Write CLI output (stdout) to log path"
      template:
        src: "templates/log.j2"
        dest: "{{ inventory_hostname }}.txt"
        mode: 0444
        force: false
        newline_sequence: '\r\n'
    #when: "hostvars.localhost.log"
      #changed_when: false

    - name: "SYS >> Parse IOS text output into structured data"
      set_fact:
        OSPF_BASIC: "{{ CLI_OUTPUT.stdout[0] | ios_ospf_basic }}"
        OSPF_NBR: "{{ CLI_OUTPUT.stdout[1] | ios_ospf_neighbor }}"
        OSPF_DB: "{{ CLI_OUTPUT.stdout[2] | ios_ospf_dbsum }}"
        OSPF_TRAF: "{{ CLI_OUTPUT.stdout[3] | ios_ospf_traffic }}"
