---
- hosts: R1
  tasks:
    - name: Collect all facts from the device
      napalm_get_facts:
        hostname: 192.168.65.101
        username: ansible
        dev_os: ios
        password: ansible
        filter: 'facts'
      register: facts
    - debug: var=facts
