---
- hosts: all
  tasks:
  - name: "Check: SNMP community {{snmp_community}} is not defined"
    ios_command:
      commands: "show snmp community"
    register: result
    failed_when: "not('name: '~snmp_community in result.stdout[0])"
  - file: path=results state=directory
    run_once: true
  - template:
      src: reports/missing-community.j2
      dest: results/errors.log
    vars:
      allhosts: "{{hostvars}}"
    run_once: true
