---
# This playbook will assemble in one file, all the result files collected

- name: Assemble the reports
  assemble:
    src:  "{{result_dir}}/roles/compliance/files/"
    dest: "{{result_dir}}/roles/compliance/files/filesassemble_report.txt"
- name: DEBUG PWD
  shell:
    cmd: "pwd"
- name: DEBUG LS
  shell:
    cmd: "ls -al ./"
# Send the result in email
- name: Send mail using Ansible
  mail:
    host: "smtp-apps.jura.ch"
    port: 25
    from: "monitoring@jura.ch"
    #username: ""
    #password: ""
    to: "fabrice.rios@swisscom.com"
    subject: "Ansible Compliance report"
    body: "{{ lookup('file', '{{result_dir}}/roles/compliance/files/filesassemble_report.txt') }}"
    secure: never #starttls
  delegate_to: localhost
  run_once: true
