---
# This playbook will assemble in one file, all the result files collected

- name: Assemble the reports
  assemble:
    src:  "{{result_dir}}/"
    dest: "{{result_dir}}/filesassemble_report.txt"

# Send the result in email
- name: Send mail using Ansible
  mail:
    host: "smtp-apps.jura.ch"
    port: 25
    from: "monitoring@jura.ch"
    #username: ""
    #password: ""
    to: "fabrice.rios@swisscom.com"
    subject: "Ansible Compliance report"
    body: "{{lookup('file', '{{result_dir}}/filesassemble_report.txt') }}"
    secure: never #starttls
  delegate_to: localhost
  run_once: true
