---
# This playbook will assemble in one file, all the result files collected

- name: Assemble the reports
  assemble:
    src:  "{{result_dir}}/"
    dest: "{{result_dir}}/filesassemble_report.txt"

# Send the result in email
- name: Send mail using Ansible
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "fabrice.rios@gmail.com"
    password: "=!XZUJ01"
    to: "fabrice.rios@gmail.com"
    subject: "Ansible Compliance report"
    body: "{{lookup('file', '{{result_dir}}/filesassemble_report.txt') }}"
    secure: starttls
  delegate_to: localhost
  run_once: true
