---
# This playbook will assemble in one file, all the result files collected

- name: Assemble the reports
  assemble:
    src: /home/fab/Dropbox/Git/Automation/RCJU_v6/roles/compliance/files
    dest: /home/fab/Dropbox/Git/Automation/RCJU_v6/roles/compliance/files/filesassemble_report.txt

