---
# Compliance check:
# Log into individual devices
# Execute show run | i aaa
# Compare printout with desired aaa config
# Report (or fail) when there’s a version mismatch


# Collect banner server information and print the result
- name: Get "show run | i aaa"    
  ios_command:
    commands: "show run | i aaa"
  register: result
- name: Print gathered facts
  debug: var=result.stdout
  tags: [print_action]

# Check if aaa conf is compliant
- name: Compliance check
  assert:
    that:
      - result.stdout is defined
      #- "'snmp-server group readonly v3 priv read SNMPv3-RO' in result.stdout[0]"
      #- "'snmp-server group readonly v3 auth read readview' in result.stdout[0]"
      #- "'snmp-server group readonly v3 priv' in result.stdout[0]"
      #- "'snmp-server view readview internet included' in result.stdout[0]"
      #- "'snmp-server view readview system included' in result.stdout[0]"
      #- "'snmp-server community {{snmp_community}} RO' in result.stdout[0]"
      #- "'snmp-server contact {{snmp_contact}}' in result.stdout[0]"
      #- "'snmp-server enable traps' in result.stdout[0]"
      #- "'snmp-server host {{snmp_host_1}} version 2c {{snmp_community}}' in result.stdout[0]"
      #- "'snmp-server host {{snmp_host_2}} version 2c {{snmp_community}}' in result.stdout[0]"
      #- "'snmp-server host {{snmp_host_3}} version 2c {{snmp_community}}' in result.stdout[0]"
      #- "'snmp-server host {{snmp_host_4}} version 3 priv readonly' in result.stdout[0]"
    fail_msg: "Fail: wrong aaa configuration"
    success_msg: "Success: aaa configured"
  ignore_errors: yes
  register: log_result

- name: Store result in file        # Store in a file the status of each device
  template:
    src: aaa.j2
    dest: "{{result_dir}}filesresult_aaa.txt"
  connection: local