---
# Compliance check:
# Log into individual devices
# Execute show run | i aaa
# Compare printout with desired aaa config
# Report (or fail) when there’s a version mismatch


# Collect banner server information and print the result
- name: Get "show run | i aaa"    
  ios_command:
    commands: "show run | i aaa"
  register: result
- name: Print gathered facts
  debug: var=result.stdout
  tags: [print_action]

# Check if aaa conf is compliant
- name: Compliance check
  assert:
    that:
      - result.stdout is defined
      - "'no aaa new-model' not in result.stdout[0]"
      - "'aaa authentication login default local' in result.stdout[0]"
      - "'aaa authentication enable default enable' in result.stdout[0]"
      - "'aaa session-id common' in result.stdout[0]"
    fail_msg: "Fail: wrong aaa configuration"
    success_msg: "Success: aaa configured"
  ignore_errors: yes
  register: log_result

- name: Store result in file        # Store in a file the status of each device
  template:
    src: aaa.j2
    dest: "{{result_dir}}/filesresult_aaa.txt"
  connection: local