--- 
# This task allows to test the import and tag mechanism
# A specific task could be executed with:  --tags <task_name>

#- name: Import NTP compliance report
#  # Warning: if no NTP server is defined, the result file does not display 
#  import_tasks: ios-compliance-ntp_napalm.yml
#  tags: ntp


#------- START CLEANING ----------
- name: DEBUG LS {{result_dir}}/roles/compliance/files/
  shell:
    cmd: "ls -al {{result_dir}}/roles/compliance/files/"
  run_once: true
  delegate_to: localhost   

- name: Ansible delete file glob
  find:
    paths: "{{result_dir}}/roles/compliance/files/"
    patterns: "*.txt"
  register: files_to_delete
  tags: 
    - assemble
    - framework_assemble
  run_once: true
  delegate_to: localhost

- name: Ansible remove file glob
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  tags: 
    - assemble
    - framework_assemble
  run_once: true
  delegate_to: localhost

- name: DEBUG LS {{result_dir}}/roles/compliance/files/
  shell:
    cmd: "ls -al {{result_dir}}/roles/compliance/files/"
  run_once: true
  delegate_to: localhost   

#------- STOP CLEANING ----------



- name: Import SYSLOG/logging compliance report
  import_tasks: ios-compliance-logging.yml
  tags: 
    - logging
    - syslog

- name: Import SSH compliance report
  import_tasks: ios-compliance-sshv2.yml
  tags: ssh

- name: Import timestamp compliance report
  import_tasks: ios-compliance-timestamp.yml
  tags: timestamp

- name: Import banner compliance report
  import_tasks: ios-compliance-banner.yml
  tags: banner

- name: Import snmp compliance report
  import_tasks: ios-compliance-snmp.yml
  tags: snmp

- name: Import aaa compliance report
  import_tasks: ios-compliance-aaa.yml
  tags: aaa

- name: Import domain compliance report
  import_tasks: ios-compliance-domain.yml
  tags: domain

- name: Import vtp compliance report
  import_tasks: ios-compliance-vtp.yml
  tags: vtp

- name: Import stp compliance report
  import_tasks: ios-compliance-stp.yml
  tags: stp

- name: Import vlan1 compliance report
  import_tasks: ios-compliance-vlan1.yml
  tags: vlan1

- name: Import miscellaneous compliance report
  import_tasks: ios-compliance-miscellaneous.yml
  tags: 
    - misc
    - miscellaneous

#- name: Import generic compliance report
#  import_tasks: ios-compliance-generic.yml
#  tags: generic

- name: Create a summary report assemblying all the reports
  import_tasks: framework_assemble.yml
  run_once: true
  delegate_to: localhost
  tags: 
    - assemble
    - framework_assemble


