--- 
# This task allows to test the import and tag mechanism
# A specific task could be executed with:  --tags <task_name>

#- name: Import NTP compliance report
#  # Warning: if no NTP server is defined, the result file does not display 
#  import_tasks: ios-compliance-ntp_napalm.yml
#  tags: ntp

- name: Import SYSLOG/logging compliance report
  import_tasks: ios-compliance-logging.yml
  tags: 
    - logging
    - syslog

- name: Import SSH compliance report
  import_tasks: ios-compliance-sshv2.yml
  tags: ssh

- name: Import timestamp compliance report
  import_tasks: ios-compliance-timestamp.yml
  tags: timestamp

- name: Import banner compliance report
  import_tasks: ios-compliance-banner.yml
  tags: banner

- name: Import snmp compliance report
  import_tasks: ios-compliance-snmp.yml
  tags: snmp

#- name: Import generic compliance report
#  import_tasks: ios-compliance-generic.yml
#  tags: generic

- name: Create a summary report assemblying all the reports
  import_tasks: framework_assemble.yml
  run_once: true
  delegate_to: localhost
  tags: framework_assemble


